#!/bin/sh
### BEGIN INIT INFO
# Provides:          si-i2p-plugin
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       <DESCRIPTION>
### END INIT INFO

SCRIPT=/usr/local/bin/si-i2p-plugin.sh
RUNAS=sii2pplugin

PIDFILE=/var/run/si-i2p-plugin/si-i2p-plugin.pid
RUNFOLDER=/var/run/si-i2p-plugin
LOGFILE=/var/log/si-i2p-plugin/si-i2p-plugin.log

start() {
  if [ -f "$PIDFILE" ]; then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting destination-isolating proxy service…' >&2
  start-stop-daemon -S -b -g "$RUNAS" -c "$RUNAS" -p "$PIDFILE" --exec "$SCRIPT"
  echo $! > "$PIDFILE"
  echo "Service started: start-stop-daemon -S -b -g $RUNAS -c $RUNAS -p $PIDFILE --exec $SCRIPT" >&2
  cat "$PIDFILE" >&2
}

stop() {
  if [ ! -f "$PIDFILE" ]; then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping destination-isolating proxy service…' >&2
  start-stop-daemon -K -g "$RUNAS" -c "$RUNAS" -p "$PIDFILE" --exec "$SCRIPT"
  echo "Service stopped start-stop-daemon -K -g $RUNAS -c $RUNAS -p $PIDFILE --exec $SCRIPT" >&2
  rm -f "$PIDFILE"
}

status() {
  if [ -f "$PIDFILE" ]; then
    start-stop-daemon -T -g "$RUNAS" -c "$RUNAS" -p "$PIDFILE" --exec "$SCRIPT"
    echo 'Currently open pipes:' >&2
    ls /var/run/si-i2p-plugin/* >&2
    tail $LOGFILE >&2
    return 1
  else
    echo 'Service not running' >&2
    ls /var/run/si-i2p-plugin >&2
    return 1
  fi
  echo 'Starting destination-isolating proxy service…' >&2
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
    update-rc.d -f si-i2p-plugin remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac
