FROM golang
RUN adduser --system --no-create-home --disabled-password --disabled-login --group sii2pplugin
COPY . /opt/
RUN chown -R sii2pplugin /opt/
WORKDIR /opt/
RUN go get github.com/eyedeekay/gosam
CMD make
