FROM alpine:edge
RUN apk update -U
RUN apk add go go-tools go-doc git make
RUN adduser -S -H -D sii2pplugin sii2pplugin
COPY . /opt/
RUN chown -R sii2pplugin /opt/
WORKDIR /opt/
RUN go get github.com/eyedeekay/gosam
CMD make
