#!/bin/sh
### BEGIN INIT INFO
# Provides:          si-i2p-plugin
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       <DESCRIPTION>
### END INIT INFO

SCRIPT=/usr/local/bin/si-i2p-plugin.sh
RUNAS=sii2pplugin

PIDFILE=/var/run/si-i2p-plugin.pid
LOGFILE=/var/log/si-i2p-plugin/si-i2p-plugin.log

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting destination-isolating proxy service…' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || kill -0 $(cat "$PIDFILE") ; then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping destination-isolating proxy service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

status() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Currently open pipes:' >&2
    su -c 'ls /var/si-i2p-plugin' $RUNAS >&2
    su -c 'tail "$LOGFILE" $RUNAS' >&2
    return 1
  else
    echo 'Service not running' >&2
    su -c 'ls /var/si-i2p-plugin' $RUNAS >&2
    return 1
  fi
  echo 'Starting destination-isolating proxy service…' >&2
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
    update-rc.d -f si-i2p-plugin remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  uninstall)
    uninstall
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac
